### ISSUE TITLE
Investigate the possibilities of reusing some of the host side functionalities on the device

### ISSUE THREAD

**Issue by mnovak42** [mnovak42/g4hepem#11]
Some of the run-time functionalities (`G4HepEmRun`), already implemented for the host side simulation, might be reused on the device side. The first targets are actually those, that relies only on the the data structures, i.e. the run-time interpolation of the macroscopic cross sections, stopping power, range, etc..

This would bring great advantage : reduce the code duplications i.e. having implementations both on the 
host and device side for these functions. 

Jonas (@hahnjo) has already started to work on this: 
https://github.com/hahnjo/g4hepem/tree/header-implementations

**Comment by mnovak42** [comment]
@hahnjo, this (https://github.com/hahnjo/g4hepem/tree/header-implementations) looks nice and interesting. 
The main issue indeed is caused by the different host and device side memory layouts that would result in different implementations. There are couple of possibilities:
 - we provide the possibility int ``G4HepEm`` to preserve the host side memory layout also in the device:
    -  **+**  : your suggested solution would work nicely 
                        &rarr; significant reduction of the device side physics functionality to be implemented 
                        &rarr; all the advantage of single implementation, e.g. no any code divergence.
    - **-**  : might not be very efficient on the device side 
                       &rarr; needs to be seen first, i.e. having a working GPU prototype might have higher priority 
                       &rarr; then one could argue, that this performance issue need to be investigated after 

 - we can provide two implementations of these ``G4HepEmRun`` functions:
    - the current one, according to the hots side data structure 
    - an additional one, according to the device side data structure
        &rarr; we will lose most of the benefits of having a single implementation used both on the host and device side
        &rarr; I do not see huge difference between this solution and if: 
               - we don't change anything but 
               - we copy (more or less) the device side function implementations that are provided now in the tests into the ``G4HepEmRun`` library `.cu` files 
               - in a way that is done in the ``G4HepEmData``

From these above I would prefer the first one as primary solution. Then later on, when your GPU prototype already works, this might be re-evaluated.

**Comment by hahnjo** [comment]
I agree that it is desirable and beneficial (in terms of flexibility) to first go for the simplest possible solution and then re-evaluate once there is need. What needs to decided then is a strategy for the currently existing code for the changed data layout: Having two schemes requires twice the space on the device which is, generally speaking, a scarce resource. On the other hand, hiding the code behind conditional compilation bears the risk of breaking it over time while other changes happen during R&D.

One point I've been thinking about in the past days is the expected benefit from the changed device layout: As far as I understand, the electron data is used for interpolation with the indices depending on a) the current material and b) the particle's kinetic energy. However, the effect of memory coalescing only improves performance if neighboring threads access neighboring data elements, which I'm not sure will actually happen in the average case. So while the AoS approach matches the general recommendations, I find it hard to project the resulting performance. Do you happen to have data on this?

**Comment by hahnjo** [comment]
I've now also "ported" `TestElemSelectorData` and `TestXSectionData` to re-use the host code. Overall this looks very feasible to me when having the same data layout available on the device. It remains to be seen if a similar strategy might work for the functions involving the RNG and how efficient the whole thing is, but I'm convinced that this gets a GPU prototype forward much easier and faster.

**Comment by mnovak42** [comment]
Sounds good. It was clear to me that it will work nicely for all these integrated data (i.e. cross sections and loss data) since they follow similar patterns. It's already good and saves up significant code duplications for you on the device. There will be even more with the gamma interactions. The other run-time functionalities, that are more specific and depend on the track representation or random number generator, will need to be seen later.  

The current device side layout might have performance benefits but (as I mention in the documentation or in the Readme-s) all these depend on how these data are used at the end in the GPU application. If the tracks, accessing the cross section data (e.g. during the step limit phase) are such that they are in the same volume, they will access data for one material cuts couple. Moreover, if the tracks are sorted according to their kinetic energy then the current structure might have some advantage over the hots side layout. It has not been measured yet and needs to be seen during a realistic shower generation. What is for sure, the current host side layout won't have much benefits on the device side.    

However, as long as the benefit of using different host and device side memory layout is not clear but having the same layout would definitely have some advantage (e.g. by reducing code duplications making possible to reuse some of the related host side codes) I'm fine with using the same layout. We can see this at the beginning of the next year and drop all the differences. Later on, when the device side simulation will work, one can investigate the net advantage (gain vs cost) of using different device side memory layouts.

**Comment by hahnjo** [comment]
To revisit this topic, do I understand correctly that the path forward is to remove the device side layout for now and re-evaluate possible gains later on? We probably have to think how to do this without breaking the CUDA tests in between; or maybe that's even not really important for an R&D project?

**Comment by mnovak42** [comment]
Yes, you understand correctly. I will remove all differences between the host and device side memory layouts this week. I will also complete the data transfer (i.e. making available the Seltzer-Berger sampling tables on the device as well) and modify the related documentations.  This should be done within a  week or so then we can restore the related CUDA tests and proceed further along this line if you are fine with this.

**Comment by hahnjo** [comment]
Sounds good, thanks for taking the first steps here :+1:

**Comment by mnovak42** [comment]
The issue is resolved according to the above discussion: the same electron data memory layout is used now on the host and device sides.
