### ISSUE TITLE
Checking required optimization and other flags

### ISSUE THREAD

**Issue by drbenmorgan** [mnovak42/g4hepem#29]
Briefly discussed offline, so just following up here with some investigations. The main issue is that @mnovak42 found some performance degradation in TestEm3 after some of the recent CMake changes. We suspected a missing optimization flag or similar, but needed some further checks

Checking the compile of the current `master` of g4hepem, I've confirmed the optimization flag (from `CMAKE_BUILD_TYPE`) is passed through properly. So that part is fine, and the issue must come from _not_ passing through one or more of the Geant4 flags (`Geant4_CXX_FLAGS`). This could well be the `-ftls-model` option, but not sure.

@mnovak42, could you let me know what the contents of the `Geant4_CXX_FLAGS` are for the install you are working with please? Also, if there's a simple run of the tests that will show the slowdown, let me know and I'll try and reproduce locally.

**Comment by mnovak42** [comment]
Hi @drbenmorgan, I hope these details below helps. 


OS, compiler, CMake, Geant4 and G4HepEm  versions
------------------------------------------------------

OS:              macOS High Sierra Version 10.13.6 
Compiler:   AppleClang 10.0.0.10001145
CMake:       version 3.19.3 
Geant4:      10.7. MT build
G4HepEm: the current master 

My `Geant4` (10.7.) build
--------------------------

Having a `Geant4` build with `Release` build type (using `ccmake .` in my Geant4 build directory gives among others): 

     CMAKE_BUILD_TYPE  Release 


Building `G4HepEm`
-------------------

1. Not specifying the `CMAKE_BUILD_TYPE` 
...........................................................................

   Expected: expected to have the same build type as `Geant4`. In `g4hepem/build`

       cmake ../ -DCMAKE_INSTALL_PREFIX=/Users/mnovak/opt/G4HepEm/ -DGeant4_DIR=/Users/mnovak/opt/Geant4-10.7-MT/lib/Geant4-10.7.0/
       ccmake . 

       CMAKE_BUILD_TYPE

   i.e. no build type set. On the same time, the content of `CXX_FLAGS` in `build/G4HepEm/CMakeFiles/g4HepEm.dir/flags.make` is 

       CXX_FLAGS = -fPIC -fPIC -std=c++11

  After building and installing `G4HepEm` and going to the `g4hepem/apps/examples/TestEm3` and building the application as 

       cmake ../ -DG4HepEm_DIR=/Users/mnovak/opt/G4HepEm/lib/cmake/G4HepEm/ -DGeant4_DIR=/Users/mnovak/opt/Geant4-10.7-MT/lib/Geant4-10.7.0/

  and executing as 

       ./TestEm3 -m ../ATLASbar.mac 

  gives 

       ======================================================
        Time:  User=136.500000s Real=34.738351s Sys=0.100000s [Cpu=393.2%]
       ======================================================

     
        
2. Explicitly specifying the `CMAKE_BUILD_TYPE` to be `Release`
............................................................................................................

   Expected: expected to have `Release` build type. In `g4HepEm/build`

       cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/mnovak/opt/G4HepEm/ -DGeant4_DIR=/Users/mnovak/opt/Geant4-10.7-MT/lib/Geant4-10.7.0/
       ccmake . 

       CMAKE_BUILD_TYPE                 Release

   i.e. build type set now as expected. The content of `CXX_FLAGS` in `build/G4HepEm/CMakeFiles/g4HepEm.dir/flags.make` is now 

       CXX_FLAGS = -O3 -DNDEBUG -fPIC -fPIC -std=c++11

   After building and installing `G4HepEm` and going to the `g4hepem/apps/examples/TestEm3` and building the application as 

        cmake ../ -DG4HepEm_DIR=/Users/mnovak/opt/G4HepEm/lib/cmake/G4HepEm/ -DGeant4_DIR=/Users/mnovak/opt/Geant4-10.7-MT/lib/Geant4-10.7.0/

   and executing as 

        ./TestEm3 -m ../ATLASbar.mac 

   gives 

       ======================================================
        Time:  User=81.640000s Real=20.797068s Sys=0.030000s [Cpu=392.7%]
       ======================================================
   

3. Same as 2. above but adding `set(CMAKE_CXX_FLAGS "${Geant4_CXX_FLAGS}")`
...........................................................................................................................................

   This above line has been added to the `g4hepem/CMakeLists.txt` right after `Geant4` has been found. 
   Configuring `G4HepEm` as above at 2., gives now `CXX_FLAGS` in `build/G4HepEm/CMakeFiles/g4HepEm.dir/flags.make` 

       CXX_FLAGS = -W -Wall -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-variadic-macros -Wshadow -pipe -Qunused-arguments -DGL_SILENCE_DEPRECATION -stdlib=libc++ -pthread -ftls-model=initial-exec -std=c++11 -O3 -DNDEBUG -fPIC -fPIC -std=c++11

   After building and installing `G4HepEm`, running the `TestEm` application 

       ======================================================
        Time:  User=79.260000s Real=20.196011s Sys=0.020000s [Cpu=392.6%]
       ======================================================


Expected
------------

The `CMake` configuration used at 1. should produce what it seen at 3. regarding the `CMAKE_BUILD_TYPE` type (should be the same as the `Geant4` dependency by default) and the `CXX_FLAGS` should also be the same as in Geant4 by default.

**Comment by drbenmorgan** [comment]
Thanks @mnovak42, what I'll do _for now_ is prepare a PR that will default the build type to Release to match what Geant4 does. I'll double check then what the effect of the different flags is with TestEm3.

**Comment by drbenmorgan** [comment]
O.k., build mode defaulted to `Release` in #31 so that should fix things for now. With `ATLASBar.mac` and similar settings, I can't observe a difference between the average runtime of `TestEm3` with and without `Geant4_CXX_FLAGS`. This doesn't mean there isn't one, but we'll need longer runs to see anything, and the only flag that I can see making a difference is ` -ftls-model=initial-exec`.
