### ISSUE TITLE
Formats for persisting G4HepEmData

### ISSUE THREAD

**Issue by drbenmorgan** [mnovak42/g4hepem#36]
Hi @mnovak42, before I fully start to implement the persistency for `G4HepEmData` and the data it holds, do you have any preferences/opinions on what format(s) to use? The data is pretty straightforward, so that helps, and of course we would keep the de/serialization code decoupled from the core `G4HepEmData`. There are a variety of options I can think of in rough order of increasing dependency:

- Plaintext (but at the cost of writing an deserialisation parser)
- JSON (using `nlohmann_json` or similar)
- HDF5
- ROOT

I'm tempted to start with plaintext/json _just_ to confirm data I/O and understand the structure, but if there are strong objections to this I can start with the preferred system!

**Comment by mnovak42** [comment]
I would prefer as little dependence as possible but of course with one that minimising your work as well. Something from the top part (definitely not root) I'm fine. 

By the way, you can always have a look to the `CopyToDevice` functions implementation of the data structures to see more details on the data (e.g. the size of the arrays).
