### ISSUE TITLE
Persisting G4HepEmParameters together with G4HepEmData

### ISSUE THREAD

**Issue by drbenmorgan** [mnovak42/g4hepem#45]
As discussed in meetings and in https://github.com/apt-sim/AdePT/issues/70, we need to "connect up" Geant4 and AdePT/Vecgeom materials/solids/physics. The `G4HepEmData` and GDML sides are taken care of or in progress, one thing I noticed as missing though is `G4HepEmParameters`. This is used both for data table init and for runtime calculations, so use of `G4HepEmData` will require the corresponding `G4HepEmParameters`. In the hybrid G4+GPU case that's fine, but for the split serialize/deserialize use case, we should also serialize `G4HepEmParameters`.

There are several ways to achieve this, the neatest I've seen being @hahnjo's creation of a [`G4HepEmState` struct]( https://github.com/apt-sim/AdePT/blob/95e6309088c49d159e95b123a8aa404d25c710af/examples/TestEm3/TestEm3.cu#L40-L43)

```c++
struct G4HepEmState {
  G4HepEmData data;
  G4HepEmParameters parameters;
};
```

which would be easy to persist and has the required consistency. Should we introduce this type in `G4HepEmData` and the corresponding (de)serialization?

**Comment by drbenmorgan** [comment]
Just a gentle bump for feedback on this - it's needed to progress with apt-sim/AdePT#70 and apt-sim/AdePT#87, and I think it'd be a generally useful `struct` as there are a few places where parameters and data have to be passed together in `G4HepEmRun`.

I have a rough implementation (and corresponding persistancy) but thinking about the above, I'm not sure if

```c++
struct G4HepEmState {
  G4HepEmData data;
  G4HepEmParameters parameters;
};
```

or

```
struct G4HepEmState {
  G4HepEmData* data; // owned by G4HepEmState?
  G4HepEmParameters* parameters; // ditto?
};

// init/free functions
```

Either work, though the later feels more in line with the rest of G4HepEm.

**Comment by mnovak42** [comment]
Both of them are fine to me.  

Regarding their ownership:
---------------------------

`G4HepEmData` is the top level collection of data structures and do not depend on any states. A top level manager creates one object from this data structure at initialisation that can be used concurrently during the run. When `G4HepEm` is used in `Geant4`, this top level manager is the *master thread* `G4RunManger` when it initialises the physics. Similarly, when data are loaded from the disc, it's probably done by a top level manager that creates the corresponding top level `G4HepEmData` structure and holds/shares etc..

The same is true for the `G4HepEmParameters`. 

Most of the top level `G4HepEmRun` run-time functionalities, that are used heavily both on the host and device, require to pass a pointer to these data structures (that are read-only at run-time).

**Comment by drbenmorgan** [comment]
Thanks @mnovak42, I'll use pointers for consistency with the rest of `G4HepEmData` and _for now_ make it a non-owning(*) "view" of the parameters and data.

(*) i.e. it will simply hold the pointers and never manipulate them (i.e. allocate or deallocate).
