### ISSUE TITLE
High-res logos

### ISSUE THREAD

**Issue by bernhardmgruber** [mnovak42/g4hepem#86]
Hi!
I would like to place the g4hepem logo into a presentation I want to give at ACAT22. Do you have higher-resolution logos than the ones in https://github.com/mnovak42/g4hepem/tree/master/docs/source/logos?
Thx!

**Comment by mnovak42** [comment]
No, unfortunately only those.

**Comment by mnovak42** [comment]
closing this as no higher resolution logo will be provided

**Comment by mnovak42** [comment]
closing this as no higher resolution logo will be provided

**Comment by mnovak42** [comment]
closing this as no higher resolution logo will be provided

**Comment by mnovak42** [comment]
closing this as no higher resolution logo will be provided
