### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by mnovak42** [mnovak42/g4hepem#9]
@mnovak42 I think it would be good to add a license to the project to avoid any confusion...

_Originally posted by @hahnjo in https://github.com/mnovak42/g4hepem/issues/8#issuecomment-745197507_

**Comment by mnovak42** [comment]
@hahnjo do you have suggestions

**Comment by hahnjo** [comment]
@mnovak42 not an expert, it should probably be compatible with the "Geant4 Software License". The conditions look custom to me, so the well-known license compatibility sheets don't apply here...

**Comment by mnovak42** [comment]
Following a discussion with my Geant4 colleagues, the same license has been added that is used by Geant4 (eventually it's a contribution of the collaboration). 
See the corresponding commit: mnovak42@37b558251cf609757fe932e006e8222133fc5f6f.
