### ISSUE TITLE
How to cite this project?

### ISSUE THREAD

**Issue by bernhardmgruber** [mnovak42/g4hepem#97]
I would like to cite this project in an upcoming publication. So far I have put together this bibtex entry:
```
@misc{G4HepEm,
	author = {Mihaly Novak and Jonas Hahnfeld and Ben Morgan and Stephan Hageböck},
	title = {The G4HepEm R\&D Project},
	year = {2022},
	publisher = {GitHub},
	howpublished = {\url{https://github.com/mnovak42/g4hepem}}
}
```
Could you please tell me if this is appropriate for you?

In the long run, it may be beneficial to add a [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file to your repository, so people can find this information faster.

Thank you!

**Comment by mnovak42** [comment]
It's fine at the moment. 
We are working on a paper describing the project that will be the main reference later.

**Comment by bernhardmgruber** [comment]
OK great, thx! Good luck with your paper!
